CREATE TABLE GENDERS (
	ID NUMBER(1) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	CONSTRAINT GENDERS_PK PRIMARY KEY (ID),
	CONSTRAINT GENDERS_UK UNIQUE (NAME)
);

CREATE TABLE JOBS (
	ID NUMBER  GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	SALARY NUMBER(9,2) NOT NULL,
	CONSTRAINT JOBS_PK PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYEES (
	ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
	GENDER_ID NUMBER(1) NOT NULL,
	JOB_ID NUMBER NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	BIRTHDATE DATE NOT NULL,
	CONSTRAINT EMPLOYEES_PK PRIMARY KEY (ID),
	CONSTRAINT EMPLOYEES_UK UNIQUE (NAME, LAST_NAME)
);

CREATE TABLE EMPLOYEE_WORKED_HOURS (
	ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
	EMPLOYEE_ID NUMBER NOT NULL,
	WORKED_HOURS NUMBER(3,0) NOT NULL,
	WORKED_DATE DATE NOT NULL,
	CONSTRAINT EM_WKED_HRS_PK PRIMARY KEY (ID)
);


CREATE OR REPLACE PROCEDURE insertEmployee(
	   p_gender_id IN EMPLOYEES.GENDER_ID%TYPE,
	   p_job_id IN EMPLOYEES.JOB_ID%TYPE,
	   p_name IN EMPLOYEES.NAME%TYPE,
	   p_last_name EMPLOYEES.LAST_NAME%TYPE,
	   p_birth IN EMPLOYEES.BIRTHDATE%TYPE,
	   v_id OUT EMPLOYEES.ID%TYPE)
IS
BEGIN

	INSERT INTO EMPLOYEES (GENDER_ID, JOB_ID, NAME, LAST_NAME, BIRTHDATE) 
	VALUES(p_gender_id, p_job_id, p_name, p_last_name, p_birth) 	
	returning ID into v_id;

END;


CREATE OR REPLACE FUNCTION getEmployeeWorkedHours(p_employee_id NUMBER, p_ini DATE, p_end DATE)
	RETURN NUMBER 
	IS v_work_hours NUMBER;
BEGIN   
    v_work_hours := 0;
	SELECT SUM(WORKED_HOURS) INTO v_work_hours FROM EMPLOYEE_WORKED_HOURS 
	WHERE EMPLOYEE_ID = p_employee_id AND WORKED_DATE BETWEEN p_ini AND p_end;

	RETURN v_work_hours;
END;


CREATE OR REPLACE FUNCTION getEmployeePaymentWorkedHours(p_employee_id NUMBER, p_ini DATE, p_end DATE) RETURN NUMBER
	AS 
	v_payment NUMBER(11,2);
	v_payment_hour NUMBER(10,2);
   BEGIN
	  
	 v_payment :=0;
	   
     SELECT (job.SALARY/30)/8 INTO v_payment_hour FROM EMPLOYEES emp 
     INNER JOIN JOBS job ON(job.ID = emp.JOB_ID) WHERE emp.ID = p_employee_id;      
      
     IF v_payment_hour IS NOT NULL 
     THEN
     	SELECT (getEmployeeWorkedHours(p_employee_id, p_ini, p_end)*v_payment_hour) INTO v_payment FROM DUAL;
     END IF;
     RETURN v_payment; 
END;



ALTER TABLE EMPLOYEES ADD CONSTRAINT EMPLOYEES_GENDERS_FK FOREIGN KEY (GENDER_ID) REFERENCES GENDERS(ID);
ALTER TABLE EMPLOYEES ADD CONSTRAINT EMPLOYEES_JOBS_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS(ID);

ALTER TABLE EMPLOYEE_WORKED_HOURS ADD CONSTRAINT EMPLOYEE_WORKED_HOURS_EMPLOYEES_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID);

INSERT INTO GENDERS (ID, NAME) VALUES(1, 'HOMBRE');
INSERT INTO GENDERS (ID, NAME) VALUES(2, 'MUJER');

INSERT INTO JOBS (NAME, SALARY) VALUES('DEVELOPER JR', 20000.10);
INSERT INTO JOBS (NAME, SALARY) VALUES('DEVELOPER SR', 55000.22);
INSERT INTO JOBS (NAME, SALARY) VALUES('LIDER TECNICO', 75000.33);

INSERT INTO EMPLOYEES (GENDER_ID, JOB_ID, NAME, LAST_NAME, BIRTHDATE) VALUES(1, 2, 'JOSE', 'LOPEZ', TIMESTAMP '1981-07-18 00:00:00.000000');

INSERT INTO EMPLOYEE_WORKED_HOURS (EMPLOYEE_ID, WORKED_HOURS, WORKED_DATE) VALUES(select ID from EMPLOYEES where NAME = 'JOSE' and LAST_NAME ='LOPEZ', 8, TIMESTAMP '2022-08-01 00:00:00.000000');
INSERT INTO EMPLOYEE_WORKED_HOURS (EMPLOYEE_ID, WORKED_HOURS, WORKED_DATE) VALUES(select ID from EMPLOYEES where NAME = 'JOSE' and LAST_NAME ='LOPEZ', 10, TIMESTAMP '2022-08-02 00:00:00.000000');
INSERT INTO EMPLOYEE_WORKED_HOURS (EMPLOYEE_ID, WORKED_HOURS, WORKED_DATE) VALUES(select ID from EMPLOYEES where NAME = 'JOSE' and LAST_NAME ='LOPEZ', 11, TIMESTAMP '2022-08-03 00:00:00.000000');
INSERT INTO EMPLOYEE_WORKED_HOURS (EMPLOYEE_ID, WORKED_HOURS, WORKED_DATE) VALUES(select ID from EMPLOYEES where NAME = 'JOSE' and LAST_NAME ='LOPEZ', 12, TIMESTAMP '2022-08-04 00:00:00.000000');
INSERT INTO EMPLOYEE_WORKED_HOURS (EMPLOYEE_ID, WORKED_HOURS, WORKED_DATE) VALUES(select ID from EMPLOYEES where NAME = 'JOSE' and LAST_NAME ='LOPEZ', 13, TIMESTAMP '2022-08-05 00:00:00.000000');

